/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    "概览",
    {
      type: "category",
      label: "开发者指南",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "开发者指南" }],
    },
    {
      type: "category",
      label: "数据质量",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "数据质量" }],
    },
    {
      type: "category",
      label: "数据集成",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "数据集成" }],
    },
    {
      type: "category",
      label: "数据开发",
      link: {
        type: "generated-index",
        description: "Examples demonstrating the usage of CLI commands.",
      },
      items: [{ type: "autogenerated", dirName: "数据开发" }],
    },
   
    {
      type: "category",
      label: "BI报表",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "BI报表" }],
    },

    {
      type: "category",
      label: "平台监控",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "平台监控" }],
    },    
    {
      type: "category",
      label: "关于修改本项目",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "关于修改本项目" }],
    },
    "faq",
    "comminicate"
    
    // {
    //   type: "category",
    //   label: "Business Image Construction Process",
    //   link: {
    //     type: "generated-index",
    //   },
    //   items: [{ type: "autogenerated", dirName: "业务镜像构建流程" }],
    // },
    // {
    //   type: "category",
    //   label: "Developers",
    //   items: ["CONTRIBUTING", "DEVELOPGUIDE"],
    // },
    // "标准协议",
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
